server:
  port: 8090

spring:
  #  main:
  #    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 180s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config-3.json
    openai:
      base-url: https://apis.itedus.cn/
      api-key: sk-6xgZRvuMvgoFfHvk8902BcDcF25b49819592164f1f45219a
      chat:
        options:
          model: gpt-4o
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://2f7e34bc8ccf4737adc0-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
